Gdx 348 favicon
co-cddo/data-catalogue pull request #26
Opened 2023-02-13 15:40 UTC by HarleyBurrowTPX

Added Govuk favicon asset

2023-02-13 16:41 UTC, MaddieWTPX approved these changes

2023-02-13 17:00 UTC, ngw requested changes

2023-02-13 17:00 UTC, ngw commented on Gemfile.lock
>      nokogiri (1.14.1-arm64-darwin)
This is odd, should be locked to the linux version...

2023-02-13 17:05 UTC, ngw commented on Gemfile.lock
>      nokogiri (1.14.1-arm64-darwin)
Ok, considering you're already there, can you remove Gemfile.lock and rebuild the image and see if that works?

2023-02-14 10:29 UTC, ngw commented on Gemfile.lock
>      nokogiri (1.14.1-arm64-darwin)
done

2023-02-14 10:29 UTC, ngw approved these changes

2023-02-15 11:48 UTC, merged